export const ERROR_CODES = {
  FORBIDDEN: 'FORBIDDEN',
  MESSAGE_EMPTY: 'MESSAGE_EMPTY',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  ROOM_NAME_TAKEN: 'ROOM_NAME_TAKEN',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
